"""Modify models

Revision ID: 12f04d458dfc
Revises: d3276c4f32bc
Create Date: 2024-03-16 16:03:56.798158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f04d458dfc'
down_revision: Union[str, None] = 'd3276c4f32bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'label')
    # ### end Alembic commands ###
