name: Upload Python Package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
        continue-on-error: false
  test:
    runs-on: ubuntu-latest
    needs: pre-commit
    services:
      db-test:
        image: postgres:14.0
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_DB: object-detection-test
        ports:
          - 5500:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
        # Run the tests. I'm using pytest and the file is in the tests directory.
      - name: Create .env arquive
        run: |
          echo "DATABASE_TEST_HOST=${{ secrets.DATABASE_TEST_HOST }}" >> ./.env
          echo "DATABASE_TEST_PORT=${{ secrets.DATABASE_TEST_PORT }}" >> ./.env
          echo "DATABASE_TEST_USER=${{ secrets.DATABASE_TEST_USER }}" >> ./.env
          echo "DATABASE_TEST_NAME=${{ secrets.DATABASE_TEST_NAME }}" >> ./.env
          echo "DATABASE_TEST_PASS=${{ secrets.DATABASE_TEST_PASS }}" >> ./.env
        working-directory: microservices/object_detection
      - name: Run tests
        run: poetry run pytest */tests/test*
        working-directory: microservices

  # deploy:
  #   needs: pre-commit
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install build
  #     - name: Build package
  #       run: python -m build
  #     - name: Publish package
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}
